db:
  dbname: "lablink_db"
  user: "lablink"
  password: "lablink"
  host: "localhost"
  port: 5432
  table_name: "vms"
  message_channel: "vm_updates"

machine:
  machine_type: "g4dn.xlarge"
  image: "ghcr.io/talmolab/lablink-sleap-client-image:linux-amd64"
  ami_id: "ami-0e096562a04af2d8b"

app:
  admin_user: "admin"
  admin_password: "IwanttoSLEAP"