db:
  dbname: "lablink_db"
  user: "lablink"
  password: "lablink"
  host: "localhost"
  port: 5432
  table_name: "vms"
  message_channel: "vm_updates"

machine:
  machine_type: "g4dn.xlarge"
  image: "gghcr.io/talmolab/lablink-client-base-image:linux-amd64-c05435106f37bb9d84bd1a6052f82d7ea9f4d825-test"
  ami_id: "ami-067cc81f948e50e06"
  repository: "https://github.com/talmolab/sleap-tutorial-data.git"
  software: "sleap"

app:
  admin_user: "admin"
  admin_password: "IwanttoSLEAP"
  region: "us-west-2"