"""Tests for `lablink client unregister`."""
from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

import pytest


_ENV_BODY = (
    "# Generated by `lablink client register` on 2026-05-26\n"
    "CLIENT_ID=vm-1\n"
    "VM_NAME=vm-1\n"
    "CLIENT_SECRET=sek\n"
    "AGENT_TOKEN=agent\n"
    "REGISTER_TOKEN=reg\n"
    "ALLOCATOR_URL=http://allocator.example.com\n"
    "ALLOCATOR_HOST=allocator.example.com\n"
    "CONNECTIVITY=lan_direct\n"
    "CLIENT_IMAGE=ghcr.io/talmolab/lablink-client:latest\n"
)


@pytest.fixture
def env_file(tmp_path):
    p = tmp_path / "client.env"
    p.write_text(_ENV_BODY)
    p.chmod(0o600)
    return p


def test_unregister_happy_path_removes_container_and_env(env_file, capsys):
    """End-to-end: notify allocator, docker rm container, delete env."""
    from lablink_cli.commands import unregister

    with patch.object(unregister, "_notify_deregister") as notify, \
         patch.object(unregister, "_exec_docker_rm") as rm, \
         patch("shutil.which", return_value="/usr/bin/docker"):
        notify.return_value = True
        rm.return_value = True
        unregister.run_unregister(env_file=env_file, insecure=False, yes=True)

    notify.assert_called_once()
    rm.assert_called_once()
    assert not env_file.exists()
    out = capsys.readouterr().out
    assert "Unregistered" in out


def test_unregister_missing_env_is_idempotent(tmp_path, capsys):
    """No env file → exit 0, print 'Nothing to unregister.'."""
    from lablink_cli.commands import unregister

    missing = tmp_path / "no-such.env"
    unregister.run_unregister(env_file=missing, insecure=False, yes=True)

    out = capsys.readouterr().out
    assert "Nothing to unregister" in out


def test_unregister_malformed_env_exits_1(tmp_path):
    """Env file present but missing required keys → exit 1."""
    from lablink_cli.commands import unregister

    bad = tmp_path / "bad.env"
    bad.write_text("CLIENT_ID=vm-1\n")  # missing CLIENT_SECRET and ALLOCATOR_URL

    with pytest.raises(SystemExit) as exc:
        unregister.run_unregister(env_file=bad, insecure=False, yes=True)
    assert exc.value.code == 1


def test_unregister_allocator_unreachable_continues(env_file, capsys):
    """Best-effort: allocator unreachable → warn, continue cleanup."""
    from lablink_cli.commands import unregister

    with patch.object(unregister, "_notify_deregister", return_value=False) as notify, \
         patch.object(unregister, "_exec_docker_rm", return_value=True), \
         patch("shutil.which", return_value="/usr/bin/docker"):
        unregister.run_unregister(env_file=env_file, insecure=False, yes=True)

    notify.assert_called_once()
    assert not env_file.exists()
    out = capsys.readouterr().out
    assert "Unregistered" in out


def test_unregister_docker_missing_warns_and_continues(env_file, capsys):
    """No docker on PATH → warn, still delete env."""
    from lablink_cli.commands import unregister

    with patch.object(unregister, "_notify_deregister", return_value=True), \
         patch("shutil.which", return_value=None):
        unregister.run_unregister(env_file=env_file, insecure=False, yes=True)

    assert not env_file.exists()
    out = capsys.readouterr().out
    assert "docker not on PATH" in out


def test_unregister_unlink_failure_exits_1(env_file, capsys, monkeypatch):
    """OSError on env_file.unlink() → red error + SystemExit(1)."""
    from lablink_cli.commands import unregister

    def boom(self):
        raise OSError("permission denied")

    monkeypatch.setattr(Path, "unlink", boom)

    with patch.object(unregister, "_notify_deregister", return_value=True), \
         patch.object(unregister, "_exec_docker_rm", return_value=True), \
         patch("shutil.which", return_value="/usr/bin/docker"), \
         pytest.raises(SystemExit) as exc:
        unregister.run_unregister(env_file=env_file, insecure=False, yes=True)

    assert exc.value.code == 1
    out = capsys.readouterr().out
    assert "Failed to delete" in out


def test_unregister_prompt_aborted(env_file, capsys, monkeypatch):
    """User declines confirmation prompt → no changes, exit 0."""
    from lablink_cli.commands import unregister

    # Simulate the operator typing 'n' (or anything not 'y').
    monkeypatch.setattr("typer.confirm", lambda *a, **kw: False)
    unregister.run_unregister(env_file=env_file, insecure=False, yes=False)

    assert env_file.exists()
    out = capsys.readouterr().out
    assert "Aborted" in out
