name: Build and Test Client Service

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build lablink-client-service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: lablink-client-base/lablink-client-service
        run: |
          python -m pip install --upgrade pip
          pip install --editable .[dev]

      - name: Build package
        working-directory: lablink-client-base/lablink-client-service
        run: |
          python -m build
          twine check dist/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lablink-client-service-dist
          path: lablink-client-base/lablink-client-service/dist/
          retention-days: 1

  tests:
    name: Test lablink-client-service
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: lablink-client-service-dist
          path: dist/

      - name: List artifacts
        run: |
          echo "Artifacts in dist/:"
          ls -l dist/

      - name: Install package from artifact
        run: |
          WHL=$(ls dist/*.whl)
          pip install "$WHL[dev]"

      - name: Run tests
        run: |
          pytest tests/
