name: Build and Test Client Service

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - lablink-client-base/lablink-client-service/**
      - .github/workflows/build-and-test-pip.yml

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: lablink-client-base/lablink-client-service
        run: uv sync --all-extras

      - name: Run ruff linter
        working-directory: lablink-client-base/lablink-client-service
        run: uv run ruff check lablink_client_service tests
  tests:
    name: Test lablink-client-service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: lablink-client-base/lablink-client-service
        run: |
          uv sync --all-extras

      - name: Run tests with Coverage
        working-directory: lablink-client-base/lablink-client-service
        run: |
          WHL=$(ls dist/*.whl)
          pip install "$WHL[dev]"

      - name: Run tests
        working-directory: lablink-client-base/lablink-client-service
        run: |
          uv run pytest tests \
          --cov=lablink_client_service \
          --cov-report=xml \
          --cov-report=html
