name: CI for Lablink Services

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "packages/**"
      - ".github/workflows/ci.yml"

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Lint - ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - package: lablink-client
            python-version: "3.10"
            working-directory: packages/client
            ruff-command: "uv run ruff check src tests"
          - package: lablink-allocator
            python-version: "3.10"
            working-directory: packages/allocator
            ruff-command: "uv run ruff check src tests"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: ${{ matrix.working-directory }}
        run: uv sync --all-extras

      - name: Run ruff linter
        working-directory: ${{ matrix.working-directory }}
        run: ${{ matrix.ruff-command }}

  test:
    name: Test - ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - package: lablink-client
            python-version: "3.10"
            working-directory: packages/client
            test-command: "uv run pytest tests --cov=src/lablink_client_service --cov-report=term-missing:skip-covered --cov-report=xml --cov-report=html"
          - package: lablink-allocator
            python-version: "3.10"
            working-directory: packages/allocator
            test-command: "uv run pytest tests --ignore=tests/terraform --maxfail=1 --disable-warnings --cov=. --cov-report=xml --cov-report=term"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: ${{ matrix.working-directory }}
        run: |
          uv sync --all-extras

      - name: Run tests
        working-directory: ${{ matrix.working-directory }}
        run: ${{ matrix.test-command }}

  docker-build-test-allocator:
    name: Docker Build Test - Allocator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build allocator dev Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./packages/allocator
          file: ./packages/allocator/Dockerfile.dev
          tags: lablink-allocator-dev:test
          push: false
          load: true

      - name: Verify venv activation
        run: |
          echo "Testing venv activation..."
          docker run --rm lablink-allocator-dev:test bash -c "source /app/.venv/bin/activate && python -c 'import sys; print(\"Venv activated:\", sys.prefix); print(\"Python executable:\", sys.executable); assert \"/app/.venv\" in sys.prefix'"

      - name: Verify console scripts exist
        run: |
          echo "Testing console scripts..."
          docker run --rm lablink-allocator-dev:test bash -c "source /app/.venv/bin/activate && echo \"lablink-allocator:\" && which lablink-allocator && echo \"generate-init-sql:\" && which generate-init-sql && echo \"Console scripts found\""

      - name: Verify dev dependencies installed
        run: |
          echo "Testing dev dependencies..."
          docker run --rm lablink-allocator-dev:test bash -c 'source /app/.venv/bin/activate && python -c "
          import sys
          print(\"Checking dev dependencies:\")
          import pytest; print(\"  - pytest version:\", pytest.__version__)
          import ruff; print(\"  - ruff available\")
          import coverage; print(\"  - coverage version:\", coverage.__version__)
          print(\"Dev dependencies verified\")
          "'

      - name: Verify package imports
        run: |
          echo "Testing package imports..."
          docker run --rm lablink-allocator-dev:test bash -c 'source /app/.venv/bin/activate && python -c "
          import sys
          import warnings
          warnings.filterwarnings(\"ignore\")
          import logging
          logging.basicConfig(level=logging.ERROR)
          print(\"Importing lablink-allocator packages:\")
          from lablink_allocator_service.main import main
          print(\"  - main.main imported\")
          from lablink_allocator_service.database import PostgresqlDatabase
          print(\"  - database.PostgresqlDatabase imported\")
          from lablink_allocator_service.get_config import get_config
          print(\"  - get_config.get_config imported\")
          print(\"Package imports successful\")
          "'

      - name: Verify uv sync created proper installation
        run: |
          echo "Testing uv sync installation..."
          docker run --rm lablink-allocator-dev:test bash -c "source /app/.venv/bin/activate && pip list 2>/dev/null | grep lablink-allocator | head -1 && echo \"Package installed via uv sync\""

      - name: Verify console script entry points are importable
        run: |
          echo "Testing console script entry points can be imported..."
          docker run --rm lablink-allocator-dev:test bash -c 'source /app/.venv/bin/activate && python -c "
          from lablink_allocator.main import main as allocator_main
          from lablink_allocator.generate_init_sql import main as generate_sql_main
          assert callable(allocator_main), \"allocator main() is not callable\"
          assert callable(generate_sql_main), \"generate_init_sql main() is not callable\"
          print(\"✓ All entry points are importable and callable\")
          "'

      - name: Execute console scripts to verify they work
        run: |
          echo "Testing console script execution..."

          # Test generate-init-sql actually runs and produces SQL file
          echo "Running generate-init-sql..."
          docker run --rm lablink-allocator-dev:test bash -c 'source /app/.venv/bin/activate && generate-init-sql 2>/dev/null && test -f /app/init.sql && wc -l /app/init.sql && grep -q "CREATE TABLE" /app/init.sql && echo "generate-init-sql executed successfully"'

          # Test lablink-allocator starts (will fail without DB, but should at least attempt to run)
          echo "Attempting to start lablink-allocator..."
          docker run --rm lablink-allocator-dev:test bash -c 'source /app/.venv/bin/activate && timeout 2 lablink-allocator > /tmp/allocator_output.txt 2>&1 || true && test -s /tmp/allocator_output.txt && echo "lablink-allocator entry point executed"'
