name: End-to-End Test LabLink Client VM Infrastructure

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "lablink-allocator/lablink-allocator-service/terraform/**"
      - ".github/workflows/client-vm-infrastructure-test.yml"

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::711387140753:role/github_lablink_repository-AE68499B37C7
          aws-region: us-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: lablink-allocator/lablink-allocator-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings
