name: Test LabLink Allocator Flask Web Service

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - lablink-allocator/lablink-allocator-service/**
      - .github/workflows/lablink-allocator-service-test.yml

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    name: Build and Test LabLink Allocator Flask Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: lablink-allocator/lablink-allocator-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        working-directory: lablink-allocator/lablink-allocator-service
        run: |
          pytest --maxfail=1 --disable-warnings
