name: Build and Push Docker Images

on:
  push:
    paths:
      - "lablink-allocator/**"
      - "lablink-client-base/lablink-client-base-image/**"
      - ".github/workflows/lablink-images.yml"

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (test, prod)"
        required: true
        default: "test"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image-name: lablink-allocator-image
            dockerfile-path: ./lablink-allocator/Dockerfile
            context: .
          - image-name: lablink-client-base-image
            dockerfile-path: ./lablink-client-base/lablink-client-base-image/Dockerfile
            context: ./lablink-client-base/lablink-client-base-image
    outputs:
      git_sha: ${{ steps.get_sha.outputs.sha }}
      sanitized_platform: ${{ steps.sanitize_platform.outputs.sanitized_platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Git SHA
        id: get_sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Debug Git SHA
        run: echo "Git SHA ${{ steps.get_sha.outputs.sha }}"

      - name: Sanitize platform name
        id: sanitize_platform
        run: |
          sanitized_platform="linux/amd64" # Hardcoded for now
          sanitized_platform="${sanitized_platform/\//-}" # Replace / with -
          echo "sanitized_platform=$sanitized_platform" >> $GITHUB_OUTPUT

      - name: Generate tags
        id: generate_tags
        run: |
          REPO_OWNER="${{ github.repository_owner }}"
          PLATFORM="${{ steps.sanitize_platform.outputs.sanitized_platform }}"
          SHA="${{ steps.get_sha.outputs.sha }}"
          if [ "${{ matrix.image-name }}" == "lablink-allocator-image" ]; then
            if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
              TAGS="$(
              echo "ghcr.io/$REPO_OWNER/lablink-allocator-image:latest"
              echo "ghcr.io/$REPO_OWNER/lablink-allocator-image:$SHA"
              echo "ghcr.io/$REPO_OWNER/lablink-allocator-image:$PLATFORM-latest"
              echo "ghcr.io/$REPO_OWNER/lablink-allocator-image:$PLATFORM-terraform-1.4.6"
              echo "ghcr.io/$REPO_OWNER/lablink-allocator-image:$PLATFORM-postgres-15"
              | paste -sd "," - )"
            else
              TAGS="$(
              echo "ghcr.io/$REPO_OWNER/lablink-allocator-image:$PLATFORM-test"
              echo "ghcr.io/$REPO_OWNER/lablink-allocator-image:$SHA-test"
              echo "ghcr.io/$REPO_OWNER/lablink-allocator-image:$PLATFORM-latest-test"
              echo "ghcr.io/$REPO_OWNER/lablink-allocator-image:$PLATFORM-terraform-1.4.6-test"
              echo "ghcr.io/$REPO_OWNER/lablink-allocator-image:$PLATFORM-postgres-15-test"
              | paste -sd "," - )"
            fi
            echo "tags=$TAGS" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.image-name }}" == "lablink-client-base-image" ]; then
            if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
              TAGS="$(
              echo "ghcr.io/$REPO_OWNER/lablink-client-base-image:latest"
              echo "ghcr.io/$REPO_OWNER/lablink-client-base-image:$PLATFORM-nvidia-cuda-11.6.1-cudnn8-runtime-ubuntu20.04"
              echo "ghcr.io/$REPO_OWNER/lablink-client-base-image:$SHA"
              echo "ghcr.io/$REPO_OWNER/lablink-client-base-image:$PLATFORM-ubuntu20.04-nvm-0.40.2-uv-0.6.8-miniforge3-24.11.3"
              | paste -sd "," - )"
            else
              TAGS="$(
                echo "ghcr.io/$REPO_OWNER/lablink-client-base-image:$PLATFORM-test"
                echo "ghcr.io/$REPO_OWNER/lablink-client-base-image:$PLATFORM-nvidia-cuda-11.6.1-cudnn8-runtime-ubuntu20.04-test"
                echo "ghcr.io/$REPO_OWNER/lablink-client-base-image:$PLATFORM-$SHA-test"
                echo "ghcr.io/$REPO_OWNER/lablink-client-base-image:$PLATFORM-ubuntu20.04-nvm-0.40.2-uv-0.6.8-miniforge3-24.11.3-test"
              | paste -sd "," - )"
            fi
            echo "tags=$TAGS" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Authenticate to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile-path }}
          platforms: linux/amd64 # Hardcoded for now
          push: true
          tags: ${{ steps.generate_tags.outputs.tags }}
